name: CI/CD Pipeline with Multi-Architecture Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write
  id-token: write  # Required for OIDC (AWS auth)

jobs:

  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run unit tests with Pytest
        run: |
          pytest --junitxml=pytest-results.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-results.xml

  build-matrix:
    name: Build & Push Multi-Architecture Images
    runs-on: ubuntu-latest
    needs: run-unit-tests

    strategy:
      matrix:
        arch:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::399359779313:role/secrer_role
          aws-region: us-east-1

      - name: Retrieve DockerHub credentials from AWS Secrets Manager
        id: secrets
        run: |
          SECRET_JSON=$(aws secretsmanager get-secret-value \
            --secret-id new_secret2323 \
            --query SecretString --output text)
          echo "DOCKERHUB_USERNAME=$(echo $SECRET_JSON | jq -r .DOCKERHUB_USERNAME)" >> $GITHUB_ENV
          echo "DOCKERHUB_TOKEN=$(echo $SECRET_JSON | jq -r .DOCKERHUB_TOKEN)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push image for ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.arch }}
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/python-flask-app:${{ github.sha }}-${{ matrix.arch == 'linux/amd64' && 'amd64' || 'arm64' }}


  notify-success:
    name: Notify Success via SES
    needs: build-matrix
    if: success()
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::399359779313:role/secrer_role
          aws-region: us-east-1

      - name: Send SES success email
        run: |
          aws ses send-email \
            --from "${{ secrets.SES_FROM_ADDRESS }}" \
            --destination "ToAddresses=${{ secrets.SES_TO_ADDRESS }}" \
            --message "Subject={Data='✅ Docker Build Success'},Body={Text={Data='Build and scan for ${{ github.repository }} succeeded.'}}"

  notify-failure:
    name: Notify Failure via SES
    needs: build-matrix
    if: failure()
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::399359779313:role/secrer_role
          aws-region: us-east-1

      - name: Send SES failure email
        run: |
          aws ses send-email \
            --from "${{ secrets.SES_FROM_ADDRESS }}" \
            --destination "ToAddresses=${{ secrets.SES_TO_ADDRESS }}" \
            --message "Subject={Data='❌ Docker Build Failed'},Body={Text={Data='Build or scan for ${{ github.repository }} failed. Please check logs.'}}"
      - name: Install Trivy
        run: |
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.51.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.51.1_Linux-64bit.deb

      - name: Run Trivy image scan
        run: |
          IMAGE_TAG=${{ env.DOCKERHUB_USERNAME }}/python-flask-app:${{ github.sha }}-${{ matrix.arch == 'linux/amd64' && 'amd64' || 'arm64' }}
          trivy image --exit-code 1 --severity CRITICAL,HIGH --format table --output trivy-report-${{ matrix.arch }}.txt $IMAGE_TAG || true

      - name: Upload Trivy scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report-${{ matrix.arch }}
          path: trivy-report-${{ matrix.arch }}.txt
