name: CI/CD Pipeline for Python Flask App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  # a. Checkout Code + Unit Tests
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run unit tests with Pytest
        run: |
          pytest --junitxml=pytest-results.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-results.xml

  # c. Build Multi-Architecture Docker Images
  build-and-push:
    name: Build Multi-Arch Docker Image
    runs-on: ubuntu-latest
    needs: run-unit-tests

    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.arch }}
          push: true
          tags: your-dockerhub-username/python-flask-app:${{ github.sha }}-${{ matrix.arch }}


